// Code generated by "stringer -type=Type"; DO NOT EDIT.

package structopt

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Ignore-0]
	_ = x[Flip-1]
	_ = x[Flag-2]
	_ = x[Argument-3]
	_ = x[Subcommand-4]
}

const _Type_name = "IgnoreFlipFlagArgumentSubcommand"

var _Type_index = [...]uint8{0, 6, 10, 14, 22, 32}

func (i Type) String() string {
	if i < 0 || i >= Type(len(_Type_index)-1) {
		return "Type(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Type_name[_Type_index[i]:_Type_index[i+1]]
}
